<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Neural Network Framework (Keras)

## *Data Science Unit 4 Sprint 2 Assignmnet 3*

## Use the Keras Library to build a Multi-Layer Perceptron Model on the Boston Housing dataset

- The Boston Housing dataset comes with the Keras library so use Keras to import it into your notebook. 
- Normalize the data (all features should have roughly the same scale)
- Import the type of model and layers that you will need from Keras.
- Instantiate a model object and use `model.add()` to add layers to your model
- Since this is a regression model you will have a single output node in the final layer.
- Use activation functions that are appropriate for this task
- Compile your model
- Fit your model and report its accuracy in terms of Mean Squared Error
- Use the history object that is returned from model.fit to make graphs of the model's loss or train/validation accuracies by epoch. 
- Run this same data through a linear regression model. Which achieves higher accuracy?
- Do a little bit of feature engineering and see how that affects your neural network model. (you will need to change your model to accept more inputs)
- After feature engineering, which model sees a greater accuracy boost due to the new features?

In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, Normalizer

from tensorflow.keras.datasets import boston_housing, mnist

In [7]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

In [8]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(404, 13) (102, 13) (404,) (102,)


In [9]:
cols = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']

scaler = MinMaxScaler()
scaled_df = pd.DataFrame(scaler.fit_transform(X_train), columns=cols)
scaled_df.head()

CRIM     ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0  0.013782  0.000  0.281525   0.0  0.314815  0.499806  0.914521  0.297191   
1  0.000174  0.825  0.057551   0.0  0.061728  0.784082  0.131823  0.536537   
2  0.054984  0.000  0.646628   0.0  0.506173  0.272851  1.000000  0.021178   
3  0.000374  0.000  0.173387   0.0  0.267490  0.479473  0.325438  0.506821   
4  0.041439  0.000  0.646628   0.0  0.674897  0.545120  0.880536  0.150041   

        RAD       TAX   PTRATIO         B     LSTAT  
0  0.130435  0.227533  0.893617  1.000000  0.468819  
1  0.043478  0.305927  0.223404  0.996167  0.038079  
2  1.000000  0.913958  0.808511  0.946089  0.042219  
3  0.173913  0.068834  0.808511  1.000000  0.173289  
4  1.000000  0.913958  0.808511  0.986207  0.356512

In [10]:
scaled_test_df = pd.DataFrame(scaler.transform(X_test), columns=cols)
scaled_test_df.head()

CRIM   ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0  0.203196  0.0  0.646628   0.0  0.604938  0.556352  1.000000  0.073596   
1  0.001315  0.0  0.350073   0.0  0.333333  0.455461  0.926880  0.127736   
2  0.000547  0.0  0.173387   0.0  0.267490  0.469404  0.437693  0.384377   
3  0.014242  0.0  0.700880   1.0  0.452675  0.520720  0.923790  0.069807   
4  0.000733  0.0  0.147727   0.0  0.131687  0.495740  0.555098  0.273258   

        RAD       TAX   PTRATIO         B     LSTAT  
0  1.000000  0.913958  0.808511  0.067906  0.753863  
1  0.217391  0.466539  0.553191  0.995083  0.399558  
2  0.173913  0.068834  0.808511  1.000000  0.221026  
3  0.173913  0.411090  0.223404  0.853800  0.104029  
4  0.086957  0.112811  0.627660  0.995587  0.185155

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout
from tensorflow.keras.metrics import mae


bh_model = Sequential(name='DeepCoverModeling')

bh_model.add(Dense(13, input_dim=13, activation='relu', name='LayerAwesome'))
bh_model.add(Dense(8, activation='tanh', name='AwesomeLayer2'))
bh_model.add(Dropout(0.15, name="Dropout1"))
bh_model.add(Dense(8, activation='tanh', name='UndercoverLayer3'))
bh_model.add(Dropout(0.15, name="Dropout2"))

bh_model.add(Dense(1, activation='relu', name='LayerUndercover4'))


bh_model.compile(loss='mean_squared_error', optimizer='nadam', metrics=['mae'])
bh_model.summary()

Model: "DeepCoverModeling"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
LayerAwesome (Dense)         (None, 13)                182       
_________________________________________________________________
AwesomeLayer2 (Dense)        (None, 8)                 112       
_________________________________________________________________
Dropout1 (Dropout)           (None, 8)                 0         
_________________________________________________________________
UndercoverLayer3 (Dense)     (None, 8)                 72        
_________________________________________________________________
Dropout2 (Dropout)           (None, 8)                 0         
_________________________________________________________________
LayerUndercover4 (Dense)     (None, 1)                 9         
Total params: 375
Trainable params: 375
Non-trainable params: 0
___________________________________________________

In [14]:
bh_model.fit(X_train, y_train, epochs=1000)

Train on 404 samples
Epoch 1/1000
404/404 [==============================] - 1s 3ms/sample - loss: 539.0565 - mae: 21.2945
Epoch 2/1000
404/404 [==============================] - 0s 121us/sample - loss: 529.1058 - mae: 21.0545
Epoch 3/1000
404/404 [==============================] - 0s 101us/sample - loss: 518.3776 - mae: 20.8023
Epoch 4/1000
404/404 [==============================] - 0s 79us/sample - loss: 509.3156 - mae: 20.5845
Epoch 5/1000
404/404 [==============================] - 0s 86us/sample - loss: 498.3066 - mae: 20.3316
Epoch 6/1000
404/404 [==============================] - 0s 99us/sample - loss: 490.2293 - mae: 20.1293
Epoch 7/1000
404/404 [==============================] - 0s 77us/sample - loss: 479.9116 - mae: 19.8706
Epoch 8/1000
404/404 [==============================] - 0s 99us/sample - loss: 473.7068 - mae: 19.7242
Epoch 9/1000
404/404 [==============================] - 0s 89us/sample - loss: 462.0583 - mae: 19.4266
Epoch 10/1000
404/404 [============================

In [15]:
bh_model.evaluate(X_train, y_train)

404/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[25.731236495593986, 3.4485292]

In [16]:
bh_model.evaluate(X_test, y_test)

102/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[33.95424592261221, 4.2161145]

In [25]:
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error

histplot = bh_model.history

# Plot training & validation accuracy values
plt.plot(histplot.history['mean_absolute_error'])
plt.title('Model accuracy')
plt.ylabel('Error')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.plot(histplot.history['loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

KeyError: 'mean_absolute_error'

In [26]:
bh_model2 = Sequential(name='DeepCoverModeling2')

bh_model2.add(Dense(13, input_dim=13, activation='relu', name='Dense1'))
bh_model2.add(Dense(8, activation='tanh', name='Dense2'))
# bh_model2.add(Dense(8, activation='tanh', name='Dense3'))
bh_model2.add(Dense(1, activation='relu', name='Dense4'))

bh_model2.compile(loss='mean_squared_error', optimizer='nadam', metrics=['mae'])

bh_model2.summary()

Model: "DeepCoverModeling2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Dense1 (Dense)               (None, 13)                182       
_________________________________________________________________
Dense2 (Dense)               (None, 8)                 112       
_________________________________________________________________
Dense4 (Dense)               (None, 1)                 9         
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [27]:
bh_model2.fit(X_train, y_train, epochs=1000)

Train on 404 samples
Epoch 1/1000
404/404 [==============================] - 1s 2ms/sample - loss: 499.3662 - mae: 20.3004
Epoch 2/1000
404/404 [==============================] - 0s 74us/sample - loss: 468.1781 - mae: 19.5545
Epoch 3/1000
404/404 [==============================] - 0s 91us/sample - loss: 450.8485 - mae: 19.1581
Epoch 4/1000
404/404 [==============================] - 0s 86us/sample - loss: 443.0485 - mae: 18.9662
Epoch 5/1000
404/404 [==============================] - 0s 91us/sample - loss: 435.9836 - mae: 18.7804
Epoch 6/1000
404/404 [==============================] - 0s 79us/sample - loss: 430.4191 - mae: 18.6389
Epoch 7/1000
404/404 [==============================] - 0s 91us/sample - loss: 425.8955 - mae: 18.5188
Epoch 8/1000
404/404 [==============================] - 0s 99us/sample - loss: 421.4890 - mae: 18.3991
Epoch 9/1000
404/404 [==============================] - 0s 89us/sample - loss: 417.1867 - mae: 18.2816
Epoch 10/1000
404/404 [==============================

In [28]:
bh_model2.evaluate(X_train, y_train)
bh_model2.evaluate(X_test, y_test)

404/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[22.44659584643794, 3.7566388]

In [29]:
histplot2 = bh_model2.history

# Plot training & validation accuracy values
plt.plot(histplot2.history['mean_absolute_error'])
plt.title('Model accuracy')
plt.ylabel('Mean Absolute Error')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper right')
plt.show()

# Plot training & validation loss values
plt.plot(histplot2.history['loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper right')
plt.show()

KeyError: 'mean_absolute_error'

## Use the Keras Library to build an image recognition network using the Fashion-MNIST dataset (also comes with keras)

- Load and preprocess the image data similar to how we preprocessed the MNIST data in class.
- Make sure to one-hot encode your category labels
- Make sure to have your final layer have as many nodes as the number of classes that you want to predict.
- Try different hyperparameters. What is the highest accuracy that you are able to achieve.
- Use the history object that is returned from model.fit to make graphs of the model's loss or train/validation accuracies by epoch. 
- Remember that neural networks fall prey to randomness so you may need to run your model multiple times (or use Cross Validation) in order to tell if a change to a hyperparameter is truly producing better results.

In [30]:
(X_train2, y_train2), (X_test2, y_test2) = mnist.load_data()
print(X_train2.shape, y_train2.shape)

(60000, 28, 28) (60000,)


In [31]:
X_train2[0].shape

(28, 28)

In [32]:
X_train2[1].shape

(28, 28)

In [33]:
X_train2[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [34]:
28*28

784

In [35]:
X_train2 = X_train2.reshape(60000, 784)
X_test2 = X_test2.reshape(10000, 784)

In [36]:
X_train2 = X_train2.astype('float32')
X_test2 = X_test2.astype('float32')

In [37]:
print(y_train2)

[5 0 4 ... 5 6 8]


In [38]:
np.unique(y_train2, return_counts=True)


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949],
       dtype=int64))

In [39]:
from tensorflow.keras.utils import to_categorical

In [40]:
y_train2 = to_categorical(y_train2, num_classes=10)
y_test2 = to_categorical(y_test2, num_classes=10)

In [41]:
y_train2[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [42]:

mnist_model = Sequential(name='mnistModeling')

mnist_model.add(Dense(16, input_dim=784, activation='relu', name='Dense1'))
mnist_model.add(Dense(8, activation='relu', name='Dense2'))
mnist_model.add(Dropout(0.15, name="Dropout1"))
mnist_model.add(Dense(8, activation='relu', name='Dense3'))
mnist_model.add(Dropout(0.15, name="Dropout2"))

mnist_model.add(Dense(10, activation='softmax', name='Output'))


mnist_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
mnist_model.summary()

Model: "mnistModeling"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Dense1 (Dense)               (None, 16)                12560     
_________________________________________________________________
Dense2 (Dense)               (None, 8)                 136       
_________________________________________________________________
Dropout1 (Dropout)           (None, 8)                 0         
_________________________________________________________________
Dense3 (Dense)               (None, 8)                 72        
_________________________________________________________________
Dropout2 (Dropout)           (None, 8)                 0         
_________________________________________________________________
Output (Dense)               (None, 10)                90        
Total params: 12,858
Trainable params: 12,858
Non-trainable params: 0
_________________________________________________

In [43]:
mnist_model.fit(X_train2, y_train2, batch_size=32, epochs=100)

Train on 60000 samples
Epoch 1/100
60000/60000 [==============================] - 6s 97us/sample - loss: 2.0228 - accuracy: 0.2761
Epoch 2/100
60000/60000 [==============================] - 4s 73us/sample - loss: 1.6095 - accuracy: 0.3810
Epoch 3/100
60000/60000 [==============================] - 3s 54us/sample - loss: 1.5498 - accuracy: 0.3901
Epoch 4/100
60000/60000 [==============================] - 3s 50us/sample - loss: 1.5148 - accuracy: 0.4042
Epoch 5/100
60000/60000 [==============================] - 3s 50us/sample - loss: 1.3854 - accuracy: 0.4588
Epoch 6/100
60000/60000 [==============================] - 3s 56us/sample - loss: 1.3195 - accuracy: 0.4837
Epoch 7/100
60000/60000 [==============================] - 4s 74us/sample - loss: 1.2878 - accuracy: 0.4983
Epoch 8/100
60000/60000 [==============================] - 5s 78us/sample - loss: 1.2465 - accuracy: 0.5120
Epoch 9/100
60000/60000 [==============================] - 5s 80us/sample - loss: 1.2218 - accuracy: 0.5256
Epoch

In [44]:
scores = mnist_model.evaluate(X_test2, y_test2)
print(f'{mnist_model.metrics_names[1]}: {scores[1]*100}')

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [45]:
mnist_hist = mnist_model.history

# Plot training & validation accuracy values
plt.plot(mnist_hist.history['acc'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper right')
plt.show()

# Plot training & validation loss values
plt.plot(mnist_hist.history['loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper right')
plt.show()

KeyError: 'acc'

## Stretch Goals:

- Use Hyperparameter Tuning to make the accuracy of your models as high as possible. (error as low as possible)
- Use Cross Validation techniques to get more consistent results with your model.
- Use GridSearchCV to try different combinations of hyperparameters. 
- Start looking into other types of Keras layers for CNNs and RNNs maybe try and build a CNN model for fashion-MNIST to see how the results compare.